import { entries } from "./history.js";
import {
  MEMORY_FAMILY_EXPANSIONS,
  OBSERVATION_EXPANSIONS,
  SIMPLE_POOL_EXPANSIONS,
  THREAT_TIER_EXPANSIONS,
} from "./pool-expansions.js";

function expandedEntries(prefix, texts, defaults = {}) {
  return entries(
    prefix,
    [...texts, ...(SIMPLE_POOL_EXPANSIONS[prefix] ?? [])],
    defaults,
  );
}

export const SPECIES = expandedEntries("species", [
  "Budget-Grade Andromedan",
  "Three Raccoons Operating a Human Permit",
  "Martian Compliance Officer",
  "Venusian Moisture Criminal",
  "Grey Alien With an Expired Learner's Permit",
  "Reptilian Middle Manager",
  "Interdimensional Gas-Station Prophet",
  "Bootleg Arcturian",
  "Weaponized Cryptid Intern",
  "Sentient Area 51 Lost-and-Found Item",
  "Human-Shaped Tax Loophole",
  "Cephalopod Influencer",
  "Moon-Bred Parking Enforcement Organism",
  "Unlicensed Clone of Somebody Less Impressive",
  "Pleiadian With Questionable Hygiene Protocols",
  "Roswell Baggage-Claim Survivor",
  "Fifth-Dimensional Bar-Fight Enthusiast",
  "Federally Subsidized Goblin",
  "Cosmic Parasite Wearing Business Casual",
  "Nevada Tunnel Aristocrat",
  "Mothman Adjacent Lifeform",
  "Synthetic Human From the Clearance Aisle",
  "Alpha Centauri Noise Complaint",
  "Probationary Time Traveler",
  "Organic Malware With Knees",
  "Shape-Shifter Stuck on the Default Preset",
  "Extraterrestrial Craigslist Purchase",
  "Deep-State Emotional Support Creature",
  "Bureau-Rejected Super Soldier",
  "Carbon-Based Terms-of-Service Violation",
  "Unstable Wormhole in a Cheap Tracksuit",
  "Zeta Reticuli Divorce Attorney",
  "Undocumented Lunar Ferret",
  "Post-Human Vending Machine Incident",
  "Aquatic Alien Who Lied on the Intake Form",
  "Experimental Homunculus With Wi-Fi",
  "Cosmic Background-Radiation Heckler",
  "Dimensional Refugee From a Worse Group Chat",
  "Grey-Market Human Upgrade",
  "Mostly Legal Extraterrestrial",
]);

export const ORIGINS = expandedEntries("origin", [
  "a foreclosed moon behind Saturn",
  "the staff restroom at Groom Lake",
  "a universe where gas stations run the government",
  "the part of New Jersey the Bureau refuses to map",
  "Zeta Reticuli's least accredited trade school",
  "a refrigerated cargo hold labeled DO NOT LICK",
  "the 1997 Phoenix Lights afterparty",
  "a wormhole under a condemned Waffle House",
  "Mars, according to a receipt nobody can authenticate",
  "the Moon's unpaid internship program",
  "an abandoned clone farm outside Dulce",
  "a simulation running on a stolen office printer",
  "the federal evidence locker marked probably harmless",
  "a timeshare inside the Bermuda Triangle",
  "Europa's maximum-security aquarium",
  "the clearance rack at an intergalactic body shop",
  "a haunted satellite with poor labor standards",
  "the fifth floor of a four-story black site",
  "an asteroid legally registered as a vape shop",
  "a parallel Earth where fitted sheets won the war",
  "a classified bus station beneath Denver International",
  "the larval pool behind a cosmic Hooters",
  "a failed reality pilot the network never aired",
  "a mobile home orbiting Proxima Centauri",
  "the restricted aisle of a Nevada Spencer's Gifts",
  "an unauthorized pocket dimension in Agent J's glovebox",
  "the last functioning bathroom on Planet Nibiru",
  "a crop circle operating as a community college",
  "an alien embassy disguised as a payday lender",
  "the Bureau's experimental Florida annex",
]);

export const ANOMALIES = expandedEntries(
  "anomaly",
  [
    "one testicle classified as carry-on luggage and the other still missing in customs",
    "a vestigial third nipple that receives encrypted weather alerts",
    "kneecaps installed backward by an unlicensed clone mechanic",
    "a liver that files a separate tax return",
    "two hearts, both emotionally unavailable",
    "a detachable spine with a manufacturer recall",
    "a digestive tract shaped like the New Jersey Turnpike",
    "one kidney broadcasting numbers-station coordinates",
    "an appendix promoted to regional manager",
    "a skull containing an emergency snack compartment",
    "three buttocks arranged in a legally actionable triangle",
    "a tongue with diplomatic immunity",
    "nostrils that migrate south during winter",
    "a pancreas running an illegal sportsbook",
    "elbows capable of opening classified PDF files",
    "a second, smaller face responsible for all bad opinions",
    "bones made from compressed gas-station receipts",
    "a reproductive system still loading the free trial",
    "a spleen with seventeen outstanding warrants",
    "hair follicles transmitting to a Russian weather balloon",
    "a tailbone that growls when the subject lies",
    "lungs optimized exclusively for vape-store oxygen",
    "a left foot registered to a deceased Nevada dentist",
    "an umbilical port compatible with obsolete Bureau hardware",
    "a rib cage assembled with furniture screws",
    "a nervous system sponsored by a discount energy drink",
    "a heart rate that syncs with nearby microwave ovens",
    "retinas displaying pop-up ads during eye contact",
    "a gallbladder containing one furious Worm Guy",
    "a pelvis that emits the Windows disconnect sound",
    "blood type listed as probably Mountain Dew",
    "an endocrine system governed by a carnival wheel",
    "a jaw hinge rated for light commercial use only",
    "fingerprints matching twelve unrelated raccoons",
    "a brain stem connected through public Wi-Fi",
    "a colon with its own chain of command",
    "ankles reinforced with confiscated UFO hull plating",
    "a naval cavity containing a tiny condemned casino",
    "a thyroid that only communicates through passive aggression",
    "one shoulder manufactured six fiscal years before the other",
    "a circulatory system routed through an undisclosed Delaware LLC",
    "ears tuned to frequencies used by divorced truckers",
    "teeth engraved with somebody else's Miranda rights",
    "a cerebellum held in place by federal optimism",
    "a phantom limb that continues posting online",
    "a torso running an unauthorized beta version of puberty",
    "a coccyx serving as an extraterrestrial docking adapter",
    "tear ducts producing low-grade transmission fluid",
    "a frontal lobe with a court-appointed supervisor",
    "an immune system that surrendered during orientation",
  ],
  { tone: "spicy", tags: ["medical"] },
);

export const SCAN_THREATS = expandedEntries("scan-threat", [
  "Mostly Harmless Unless Given a Microphone",
  "Low Risk, High Maintenance",
  "Unsupervised Kitchen Hazard",
  "Class-2 Group Chat Contaminant",
  "Weaponized Incompetence",
  "Regional Vibe Emergency",
  "Moderate Biohazard, Severe Paperwork",
  "Threat to Upholstery",
  "Interstate Emotional Spill",
  "One Drink From an International Incident",
  "Containable With Snacks",
  "Aggressively Non-Essential",
  "Cosmic Nuisance",
  "Probationary Menace",
  "High-Risk Karaoke Organism",
  "Furniture-Level Intelligence Event",
  "Civilization-Ending Dumbass",
  "Unlicensed Social Weapon",
  "Localized Reality Leak",
  "Category-Five Bathroom Event",
  "Federal Embarrassment",
  "Potentially Sentient Fire Code Violation",
  "Hostile to Basic Geometry",
  "Dangerous Near Open Tabs",
  "Containment Recommended Before Brunch",
  "Blacksite Insurance Exclusion",
  "Severe Exposure Risk to Dignity",
  "Planetary Liability With Good Wi-Fi",
  "Do Not Feed After Midnight or Payroll",
  "Omega-Level Administrative Burden",
]);

export const SCAN_WEAKNESSES = expandedEntries("scan-weakness", [
  "being asked to explain the joke",
  "stairs exceeding one standard flight",
  "a disconnected controller",
  "direct sunlight and indirect criticism",
  "the phrase please provide a source",
  "fitted sheets",
  "any door marked PUSH",
  "low-battery smoke detectors",
  "room-temperature ranch dressing",
  "eye contact from a disappointed cashier",
  "the Windows update screen",
  "a receipt longer than six inches",
  "women who know what they want for dinner",
  "basic follow-up questions",
  "the metric system",
  "a second consecutive push-up",
  "hearing their own voice recording",
  "restaurant menus without pictures",
  "the consequences of their own bit",
  "a properly fitted suit",
  "unsweetened sparkling water",
  "a captcha containing motorcycles",
  "alphabetizing anything",
  "small talk with a sober adult",
  "the shower setting labeled normal",
  "two-factor authentication",
  "a Roomba with nothing left to lose",
  "books without movie adaptations",
  "parallel parking under observation",
  "a calendar reminder marked mandatory",
  "the sound of a zipper on a body bag",
  "fiber in any recognizable form",
  "a firm handshake from somebody shorter",
  "walking past a mirror without checking",
  "cold pizza that belongs to someone else",
  "the word accountability",
  "a bartender saying we're closing",
  "any animal that can maintain employment",
  "an elevator inspection certificate",
  "being left alone with their search history",
]);

export const DISPOSITIONS = expandedEntries("disposition", [
  "Release under intense but poorly funded surveillance.",
  "Return to the wild before it learns payroll.",
  "Quarantine inside a Dave & Buster's prize counter.",
  "Issue one bus pass and deny all appeals.",
  "Assign a Worm Guy as legal guardian.",
  "Tag and release several counties away.",
  "Store upright in a cool, judgmental place.",
  "Transfer to the Bureau's Florida office as punishment.",
  "Approve for limited social use on weekends.",
  "Contain with snacks, shame, and a weighted blanket.",
  "Deport to the nearest Bass Pro Shops pyramid.",
  "Monitor until the second face asks for counsel.",
  "Return to manufacturer without original packaging.",
  "Keep away from livestock and Bluetooth speakers.",
  "Classify as furniture until behavior improves.",
  "Allow supervised internet access after 9 p.m.",
  "Neuralyze the subject, then neuralyze the neuralyzer.",
  "Place on administrative leave from humanity.",
  "Release with an ankle monitor and a juice box.",
  "Assign to extraterrestrial customer service indefinitely.",
  "Seal in evidence next to the haunted vape.",
  "Observe from a distance normally reserved for fireworks.",
  "Permit one phone call, preferably to a veterinarian.",
  "Suspend operating license pending a successful shower.",
  "Confiscate all capes, swords, and podcast equipment.",
  "Return to orbit using economy shipping.",
  "Mark as conditionally housebroken.",
  "Grant asylum inside the server's least active voice channel.",
  "Forward the entire file to somebody paid enough to care.",
  "Close the case and pretend this was weather.",
]);

export const SCAN_CONFIDENCE = expandedEntries("scan-confidence", [
  "99.7% — the scanner asked to be reassigned afterward",
  "94% — contaminated by secondhand embarrassment",
  "88% — one probe came back sticky",
  "83% — pending confirmation from a sober veterinarian",
  "76% — the other 24% resigned",
  "69% — Agent J refuses to improve that number",
  "61% — enough for government work",
  "58% — coin flip upgraded by federal confidence",
  "47% — scanner briefly detected a soul",
  "42% — the answer to a worse question",
  "36% — subject moved during the cavity search",
  "25% — instrument was purchased at an airport kiosk",
  "17% — readings conflict with basic mammal anatomy",
  "8% — Worm Guys performed the calibration",
  "2% — legally still more confidence than the subject deserves",
]);

const OBSERVATION_TEXT = {
  witness: {
    reactions: [
      "requested immediate witness protection",
      "began speaking exclusively through legal counsel",
      "locked every door and one unrelated refrigerator",
      "called the Bureau's emotional-damage hotline",
      "submitted a resignation from the species",
      "entered a monastery with surprisingly fast Wi-Fi",
      "changed their name and blood type",
      "started carrying holy water and a tire iron",
    ],
    actions: [
      "attempted to recharge a neuralyzer in a gas-station microwave",
      "used a Noisy Cricket to cauterize something no doctor had diagnosed",
      "performed an alien mating display during a fire drill",
      "sold counterfeit moon rocks from a borrowed mobility scooter",
      "tried to smuggle a live probe through airport security",
      "declared diplomatic immunity in a Taco Bell bathroom",
      "opened a wormhole using two vape batteries and spite",
      "asked a Grey alien whether it came in a men's size",
    ],
    outcomes: [
      "three federal coroners to resign and one raccoon to inherit the server",
      "a twelve-mile evacuation nobody was allowed to explain",
      "the nearest weather balloon to file a restraining order",
      "a class-action lawsuit from the concept of dignity",
      "an emergency meeting of every adult in the room",
      "the Moon to briefly mute the group chat",
      "six livestock disappearances and one suspicious Groupon",
      "a containment team to request combat pay",
    ],
    render(witness, target, reaction, action, outcome) {
      return `${witness} ${reaction} after ${target} ${action}, causing ${outcome}.`;
    },
  },
  surveillance: {
    reactions: [
      "threw a folding chair at the observation van",
      "covered the camera with a restraining order",
      "performed the sign of the cross incorrectly",
      "hid inside a vending machine for two fiscal quarters",
      "signaled for extraction using a mozzarella stick",
      "pretended to be furniture until authorities left",
      "called their mother and the Department of Energy",
      "began live-commentating the collapse of civilization",
    ],
    actions: [
      "mistook a cattle implant for a Bluetooth earbud",
      "licked condensation off a classified spacecraft",
      "challenged a Reptilian to a custody hearing",
      "attempted to parallel park a stolen saucer",
      "installed alien firmware on a gas-station toilet",
      "used crop-circle coordinates as a DoorDash address",
      "traded Earth's defense codes for loaded fries",
      "asked the mothership to circle the block",
    ],
    outcomes: [
      "ended with two missing agents and a five-star Yelp review",
      "forced the Bureau to classify an entire Applebee's",
      "left Nevada legally unable to make eye contact",
      "created a second moon nobody had budgeted for",
      "triggered a recall of every human disguise in the county",
      "made the surveillance van request witness protection",
      "was blamed on swamp gas with visible disappointment",
      "closed three highways and one very specific OnlyFans account",
    ],
    render(witness, target, reaction, action, outcome) {
      return `Bureau footage shows ${witness} ${reaction} when ${target} ${action}; the incident ${outcome}.`;
    },
  },
  medical: {
    reactions: [
      "acute exposure to secondhand mutation",
      "a stress fracture in their belief system",
      "contact embarrassment covering 40% of the body",
      "an unauthorized memory growing behind one eye",
      "intermittent screaming in a frequency reserved for dolphins",
      "a displaced sense of personal safety",
      "severe allergic reaction to government secrecy",
      "a phantom probe wound with excellent credit",
    ],
    actions: [
      "used a tractor beam to remove an ingrown hair",
      "swallowed a tracking beacon to win a bet",
      "attempted field surgery with a windshield scraper",
      "replaced their blood plasma with blue sports drink",
      "borrowed a Grey's reproductive organ without reading the manual",
      "stapled a classified implant to the wrong cheek",
      "tested alien anesthesia at a children's pizza arcade after closing",
      "used the autopsy laser to warm soup",
    ],
    outcomes: [
      "a medical chart thick enough to stop small-arms fire",
      "the quarantine of two nurses and a deeply involved janitor",
      "an organ donor card naming the federal government as victim",
      "the discovery of a new hole with no approved purpose",
      "a surgical bill addressed to Planet Earth",
      "one veterinarian earning immediate tenure",
      "the first malpractice claim filed by a corpse",
      "an ambulance being neuralyzed for its own protection",
    ],
    render(witness, target, reaction, action, outcome) {
      return `${witness} was treated for ${reaction} after ${target} ${action}, resulting in ${outcome}.`;
    },
  },
  criminal: {
    reactions: [
      "requested an armed escort to the nearest normal planet",
      "reported a crime against both science and upholstery",
      "turned state's evidence before anyone asked",
      "filed a missing-person report for their remaining innocence",
      "asked whether the death penalty applies across dimensions",
      "demanded immunity and a fresh pair of pants",
      "submitted body-camera footage in a sealed aquarium",
      "identified the suspect using smell alone",
    ],
    actions: [
      "ran an illegal probe exchange behind a bowling alley",
      "counterfeited Bureau badges on edible paper",
      "sold Area 51 visitor passes to livestock",
      "impersonated a licensed human at a parole hearing",
      "laundered moon currency through a claw machine",
      "kidnapped their own clone and demanded store credit",
      "operated a black-market organ upgrade from a Kia trunk",
      "stole a UFO and returned it with the fuel light on",
    ],
    outcomes: [
      "a duffel bag containing seventeen fake navels",
      "the original owner of the subject's left foot",
      "a neuralyzer registered to a deceased magician",
      "six pounds of uncut meteorite and one valid coupon",
      "a witness list made entirely of raccoons",
      "an alien egg paying rent in cash",
      "the murder weapon applying for unemployment",
      "a getaway saucer with dealer plates",
    ],
    render(witness, target, reaction, action, outcome) {
      return `${witness} contacted Agent J after discovering that ${target} ${action}; investigators later found ${outcome}.`;
    },
  },
  insurance: {
    reactions: [
      "a total loss of one previously functional weekend",
      "damage to property, dignity, and one load-bearing uncle",
      "unauthorized probing with a $500 deductible",
      "cosmic contamination excluded under paragraph 9",
      "emotional depreciation of a vintage nervous system",
      "the theft of twelve hours and both eyebrows",
      "a workplace mutation during unpaid lunch",
      "acts of God, aliens, and avoidable stupidity",
    ],
    actions: [
      "backed a saucer through a retaining wall",
      "used a tractor beam to repossess the wrong trailer",
      "released a pocket universe into a rental car",
      "stored antimatter beside expired potato salad",
      "neuralyzed the claims adjuster four consecutive times",
      "declared a body cavity as commercial storage",
      "took an alien parasite through an automatic car wash",
      "attempted orbital reentry without collision coverage",
    ],
    outcomes: [
      "the insurer to leave this solar system",
      "a premium increase visible from orbit",
      "one actuary to burst into sacred flame",
      "the policy to develop trust issues",
      "a deductible larger than Rhode Island",
      "the collapse of a regional lizard-person network",
      "three adjusters to join the same cult",
      "the phrase pre-existing condition to become classified",
    ],
    render(witness, target, reaction, action, outcome) {
      return `${witness} filed a federal insurance claim for ${reaction} after ${target} ${action}, causing ${outcome}.`;
    },
  },
  coroner: {
    reactions: [
      "identified the body as emotionally deceased",
      "confirmed the victim had been dead since the group chat started",
      "refused to touch the evidence without barbecue tongs",
      "requested a priest, a mechanic, and a second coroner",
      "described the smell as legally sentient",
      "signed the report using someone else's hand",
      "asked why the corpse had better posture",
      "changed the cause of death to none of my business",
    ],
    actions: [
      "performed a basement autopsy on a live weather balloon",
      "mistook embalming fluid for an energy drink",
      "attempted to clone a corpse from a browser cookie",
      "used a neuralyzer to check pupil response",
      "reanimated the wrong half of a federal witness",
      "stored alien remains in a wedding-cake freezer",
      "tried to hide evidence inside a second, louder corpse",
      "signed a death certificate before the subject finished speaking",
    ],
    outcomes: [
      "the body was innocent but the shoes were not",
      "cause of death remains aggressive customer service",
      "the deceased now owns mineral rights on Mars",
      "two organs had already retained counsel",
      "the autopsy table tested positive for Florida",
      "death occurred three years after the funeral",
      "the cadaver had been clocked in since Tuesday",
      "all further questions were redirected to a haunted fax machine",
    ],
    render(witness, target, reaction, action, outcome) {
      return `The night-shift coroner interviewed ${witness} after ${target} ${action}; ${reaction}, and the final report states ${outcome}.`;
    },
  },
};

export const OBSERVATION_FAMILIES = Object.freeze(
  Object.entries(OBSERVATION_TEXT).map(([id, value]) =>
    Object.freeze({
      id,
      reactions: entries(`observation-${id}-reaction`, [
        ...value.reactions,
        ...(OBSERVATION_EXPANSIONS[id]?.reactions ?? []),
      ]),
      actions: entries(`observation-${id}-action`, [
        ...value.actions,
        ...(OBSERVATION_EXPANSIONS[id]?.actions ?? []),
      ]),
      outcomes: entries(`observation-${id}-outcome`, [
        ...value.outcomes,
        ...(OBSERVATION_EXPANSIONS[id]?.outcomes ?? []),
      ]),
      render: value.render,
    }),
  ),
);

export const MEMORY_PERIODS = expandedEntries("memory-period", [
  "the summer your family stopped discussing",
  "three hours missing from last Tuesday",
  "the night of the 1997 Phoenix Lights",
  "your undocumented eighth birthday",
  "a Thursday that officially never occurred",
  "the weekend immediately before your first alibi",
  "the final afternoon of a previous life",
  "six minutes after the future ended",
  "an especially damp evening in 2012",
  "the tax year the Moon changed ownership",
  "your second first day at kindergarten",
  "the morning after an unlicensed funeral",
  "a leap day removed from federal calendars",
  "the summer Agent K misplaced New Mexico",
  "the night your clone learned disappointment",
  "the final shift at a classified former employer",
  "a childhood field trip listed only as livestock",
  "the week every mirror faced the wall",
  "the exact hour your search history gained consciousness",
  "the Tuesday the Bureau legally declared Wednesday",
]);

export const MEMORY_LOCATIONS = expandedEntries("memory-location", [
  "Sublevel 7 beneath a suburban laser-tag arena",
  "a motel room orbiting just outside municipal law",
  "the cold-storage chapel at Groom Lake",
  "a condemned Chuck E. Cheese beneath Denver International",
  "the autopsy bay of an unregistered moon",
  "a crop circle operating as a walk-in clinic",
  "the trunk of a Bureau sedan with diplomatic plates",
  "an alien embassy disguised as a mattress outlet",
  "the employee bathroom of a fifth-dimensional casino",
  "a mobile interrogation unit parked behind Denny's",
  "the larval nursery beneath your childhood dentist",
  "a funeral home that accepted Dogecoin",
  "the abandoned clone wing at Dulce",
  "a pocket universe inside a broken vending machine",
  "the witness-protection aisle at Home Depot",
  "an offshore black site technically inside Nebraska",
  "a Reptilian timeshare near the Bermuda Triangle",
  "the Moon's lowest-rated urgent-care clinic",
  "a classified petting zoo with no surviving goats",
  "the Bureau archive labeled DON'T MAKE IT WEIRD",
  "a decommissioned UFO parked inside a Spirit Halloween",
  "the third booth of a Waffle House that has no second booth",
  "a bunker whose only exit was the gift shop",
  "a gas station bathroom observed in three timelines",
  "the corpse-return counter at a Nevada Costco",
  "a medical shuttle with expired dealer tags",
  "the sacrificial conference room at corporate headquarters",
  "an interstellar customs desk inside your left nostril",
  "a witness room furnished entirely with shower curtains",
  "the government basement beneath another government basement",
]);

export const MEMORY_REASONS = expandedEntries("memory-reason", [
  "the incident made three senators molt on live television",
  "you learned which member of Congress is rented by the hour",
  "the mothership's warranty explicitly excluded witnesses",
  "Agent J had already filled out the easy version of the paperwork",
  "your testimony caused a corpse to request counsel",
  "the evidence knew your mother's maiden name",
  "Earth was not ready for the smell",
  "the Bureau needed your search history to remain deniable",
  "you correctly identified the President's backup skin",
  "the alien ambassador had a family plan",
  "the operation exceeded its dignity budget",
  "the timeline's insurance carrier refused coverage",
  "your clone unionized during questioning",
  "the autopsy produced a legally binding Yelp review",
  "the Moon demanded joint custody",
  "your browser cookies were classified as biological evidence",
  "the cult had already trademarked your safe word",
  "the future sent a cease-and-desist",
  "the corpse recognized you from work",
  "your remaining innocence was needed for calibration",
  "the recovered object kept calling Agent K daddy",
  "you asked one follow-up question too many",
  "the weather balloon pressed charges",
  "your alibi required a second alibi",
  "the Bureau could not neuralyze the raccoon jury",
  "somebody had to remain eligible for jury duty",
  "the organism inside you requested privacy",
  "your version of events was somehow more embarrassing",
  "the funeral was still technically in progress",
  "the probe footage tested poorly with focus groups",
  "your previous life owed the current one money",
  "the evidence locker developed separation anxiety",
  "the classified employer denied ever hiring mammals",
  "the experiment was funded by an energy-drink coupon",
  "the time traveler refused to share spoilers",
  "the witness protection program ran out of pants",
  "the phrase informed consent had left the building",
  "your skeleton failed the background check",
  "the incident created a taxable second personality",
  "everyone agreed forgetting was cheaper than therapy",
]);

export const MEMORY_EVIDENCE = expandedEntries("memory-evidence", [
  "a motel key stamped MARS — NO REFUNDS",
  "one wet Bureau badge belonging to nobody alive",
  "a Polaroid of your clone asking for a manager",
  "three teeth with different Social Security numbers",
  "a receipt for twelve gallons of embalming fluid and gum",
  "an alien egg wearing your childhood retainer",
  "a parking ticket issued on the dark side of the Moon",
  "one prosthetic buttock containing launch codes",
  "a loyalty card from the Intergalactic Organ Bazaar",
  "a voicemail recorded six years after your death",
  "a tiny tuxedo sized for the organism in your gallbladder",
  "a neuralyzer with your fingerprints and bite marks",
  "a wedding photo in which both spouses are you",
  "a jar labeled ORIGINAL PERSONALITY",
  "one livestock tag engraved with your Wi-Fi password",
  "an autopsy invoice marked customer declined to remain dead",
  "a cassette tape of you confessing in fluent dolphin",
  "a hotel Bible rewritten as a vehicle warranty",
  "a severed glove still holding your hand",
  "an Area 51 visitor badge listing your species as pending",
  "a coupon for one free reincarnation, expired",
  "a disposable camera filled with pictures of tomorrow",
  "a restraining order signed by Planet Venus",
  "the lower half of an astronaut who insists you're coworkers",
  "a taxidermied Roomba containing medical records",
  "a jar of moonlight with your DNA on the lid",
  "a body-bag zipper registered in your name",
  "an unsigned apology from the concept of medicine",
  "a keycard for Sublevel 8, which officially has seven levels",
  "a receipt showing Earth was returned for store credit",
  "a child's drawing of Agent J performing your autopsy",
  "one federal nipple clamp tagged as aerospace equipment",
  "a map of your organs with three marked for redevelopment",
  "a classified pager still receiving booty calls",
  "a court summons addressed to your previous incarnation",
  "a freezer-burned alien labeled best man",
  "an employee review praising your work as a cadaver",
  "a church bulletin advertising your cult's pancake breakfast",
  "a probe with a monogram nobody authorized",
  "a handwritten note reading HE ASKED FOR THE DELUXE PACKAGE",
]);

export const MEMORY_RESIDUALS = expandedEntries(
  "memory-residual",
  [
    "You salute whenever a microwave reaches zero.",
    "Your left knee whispers weather forecasts in Portuguese.",
    "Every fitted sheet now looks like a federal trap.",
    "You experience phantom applause during medical exams.",
    "Your reflection occasionally clocks out before you do.",
    "You can taste nearby Wi-Fi passwords.",
    "One testicle vibrates when Congress is lying; it has not stopped.",
    "You become aroused by professionally laminated credentials.",
    "Your skeleton plays the Windows startup sound at dawn.",
    "You recognize every corpse but cannot remember from where.",
    "Your dreams now include unskippable Bureau advertisements.",
    "You refer to every bathroom as the secondary airlock.",
    "A small part of you remains legally married to the Moon.",
    "Your belly button accepts obsolete charging cables.",
    "You feel homesick whenever livestock goes missing.",
    "Your handwriting changes whenever Agent K enters the room.",
    "You hiccup in Morse code during felony investigations.",
    "Your right ear receives a podcast from the year 2049.",
    "You no longer cast a shadow near federal property.",
    "Your pulse briefly stops when somebody says informed consent.",
    "You can smell whether a person has diplomatic immunity.",
    "Your spine attempts to eject during turbulence.",
    "Every vending machine calls you by your previous name.",
    "You wake with dirt beneath nails you no longer possess.",
    "Your fingerprints change after consuming ranch dressing.",
    "You become irrationally protective of unmarked white vans.",
    "Your teeth chatter whenever an alien invoice is overdue.",
    "You remember being born but not agreeing to it.",
    "A second voice narrates your bowel movements for training purposes.",
    "You cannot enter a Spirit Halloween without assuming command.",
    "Your blood pressure is now classified above your clearance.",
    "You lactate trace amounts of transmission fluid under stress.",
    "Your dreams are sponsored by an intergalactic payday lender.",
    "Your appendix sends holiday cards to a Nevada coroner.",
    "You involuntarily whisper cover story accepted after thunder.",
    "Your eyebrows point toward the nearest hidden spacecraft.",
    "You feel a phantom lanyard tightening during background checks.",
    "You can no longer distinguish déjà vu from scheduled maintenance.",
    "Your lower back contains one unread government notification.",
    "You become briefly translucent when asked where you were Tuesday.",
    "Your saliva glows around unlicensed taxidermy.",
    "You cry whenever a weather balloon is blamed.",
    "Your dreams end with a customer-satisfaction survey.",
    "Your pulse syncs to the nearest evidence-room freezer.",
    "Your left buttock remembers a war the rest of you denies.",
    "You wake every Thursday holding a different hotel key.",
    "Your nose bleeds whenever a timeline is audited.",
    "You automatically tip twenty percent at alien abductions.",
    "Your body rejects shirts without government logos.",
    "You still receive performance reviews from your own corpse.",
  ],
  { tone: "dark", tags: ["medical"] },
);

export const MEMORY_TREATMENTS = expandedEntries("memory-treatment", [
  "Avoid mirrors, livestock, and elected officials for 72 hours.",
  "Take two aspirin and return the stolen saucer before dawn.",
  "Report to Agent J with clean underwear and no legal counsel.",
  "Sleep inside a Faraday cage until the second voice clocks out.",
  "Apply holy water externally; apply bourbon according to judgment.",
  "Discontinue all gas-station supplements and amateur autopsies.",
  "Spend one weekend somewhere the Moon cannot see you.",
  "Replace browser history, smoke detector, and current alibi.",
  "Consume fiber and one legally obtained memory.",
  "Do not operate heavy machinery or become heavy machinery.",
  "Attend six sessions with a veterinarian cleared for mammals.",
  "Keep the affected organ refrigerated and emotionally supported.",
  "Avoid neuralyzers sold without a factory seal.",
  "Call the Bureau if the corpse asks for a rematch.",
  "Wear sunglasses indoors until dignity regenerates.",
  "Return all borrowed anatomy within ten business days.",
  "Remain under observation by a sober adult or qualified raccoon.",
  "Repeat this was swamp gas until the lawsuit expires.",
  "Do not feed the residual personality after midnight.",
  "Schedule a follow-up in this timeline, not the other one.",
  "Take one Worm Guy with meals for administrative support.",
  "Block the future's number and change your mother's maiden name.",
  "Avoid cult leadership until swelling decreases.",
  "Store the memory upright in a cool, dry lie.",
  "Refrain from sexual contact with government hardware.",
  "Use the emergency zipper only if the body bag begins moving.",
  "Report any new navels to local authorities.",
  "Drink water, touch grass, and stop licking spacecraft.",
  "Request a replacement childhood from Human Resources.",
  "Agent J recommends denial, hydration, and leaving town.",
]);

export const MEMORY_CONFIDENCE = expandedEntries("memory-confidence", [
  "99% — your subconscious has retained counsel",
  "96% — confirmed by dental records from tomorrow",
  "91% — the corpse picked you from a lineup",
  "87% — witness passed two of three species tests",
  "82% — neural scar tissue matches Bureau equipment",
  "74% — supported by one credible raccoon",
  "68% — enough to ruin Thanksgiving",
  "61% — Agent J has convicted people with less",
  "55% — timeline contamination remains possible",
  "49% — literally a coin flip with paperwork",
  "38% — memory may belong to your better clone",
  "27% — recovered through airport Wi-Fi",
  "18% — witness was dead during interview",
  "9% — treatment team consisted entirely of Worm Guys",
  "3% — still more believable than your original story",
]);

const MEMORY_FAMILY_DATA = [
  {
    id: "abduction",
    incidents: [
      "woke strapped to a stainless-steel brunch table while four Greys debated whether you counted as livestock",
      "were abducted by a saucer whose crew immediately asked for a different specimen",
      "participated in a probing demonstration after lying about prior experience",
      "signed an alien release form using a crayon and somebody else's thumb",
      "were selected for first contact because every qualified adult had blocked the number",
      "escaped an examination room by convincing the ship you were contagious",
      "mistook an alien tractor beam for premium rideshare service",
    ],
    escalations: [
      "The lead examiner requested hazard pay after opening the gown.",
      "A second craft arrived solely to return your missing dignity.",
      "The procedure was halted when the probe requested reassignment.",
      "The crew voted 6–1 to release Earth back into the wild.",
      "Your medical chart was later used to frighten alien children.",
    ],
  },
  {
    id: "childhood",
    incidents: [
      "brought home a class pet that later testified before Congress",
      "won a science fair using an organ nobody remembers donating",
      "spent recess teaching a weather balloon to lie",
      "were retrieved from a crop circle wearing another child's skeleton",
      "asked your imaginary friend for diplomatic credentials and received them",
      "performed your first neuralyzation with a disposable camera",
      "were suspended for operating an extraterrestrial lemonade stand",
    ],
    escalations: [
      "The principal was replaced by a taller, wetter principal overnight.",
      "Every class photo from that year now shows a federal evidence marker.",
      "Your parents accepted hush money in the form of theme-park coupons.",
      "The school nurse still receives royalties from the mutation.",
      "Three classmates remember you hatching, but none agree from what.",
    ],
  },
  {
    id: "missing-weekend",
    incidents: [
      "checked into a motel with a Reptilian lobbyist and checked out as your own emergency contact",
      "entered a karaoke contest on Mars using a dead senator's identity",
      "spent forty-eight hours operating an illegal clone car wash",
      "woke in a crop circle wearing a tuxedo and one federal ankle monitor",
      "lost Earth in a card game and spent Sunday winning it back",
      "joined an alien bachelor party that ended in a livestock tribunal",
      "drove a Bureau sedan through three timelines and one Wendy's",
    ],
    escalations: [
      "The minibar charged you for antimatter and emotional damages.",
      "Security footage shows your clone leaving several hours before you arrived.",
      "The hotel manager identified you by the sound of your organs.",
      "Nobody can explain the wedding ring welded to your ankle.",
      "Monday was cancelled in two counties while cleanup continued.",
    ],
  },
  {
    id: "previous-life",
    incidents: [
      "served as a respected alien veterinarian until the malpractice comet",
      "were a medieval executioner known for letting the equipment improvise",
      "lived as a moon priest who worshipped an unusually confident Roomba",
      "worked as the left half of a famous conjoined psychic",
      "commanded a starship that surrendered to a parking ticket",
      "were reincarnated after losing a bar fight with your own skeleton",
      "served three lifetimes as a Reptilian divorce mediator",
    ],
    escalations: [
      "Your former spouse has filed for backdated alimony across incarnations.",
      "The murder weapon remains emotionally attached to you.",
      "A portrait from 1642 shows you making the exact same bad decision.",
      "Your previous corpse has requested the current body's forwarding address.",
      "The karmic debt now exceeds the value of your available organs.",
    ],
  },
  {
    id: "experiment",
    incidents: [
      "volunteered for a super-soldier trial after mistaking the consent form for a sandwich menu",
      "were injected with experimental confidence harvested from used-car salesmen",
      "tested a teleportation device that moved everything except your underwear",
      "joined a federal program designed to make one average man slightly damper",
      "received a prototype liver with ad-supported functionality",
      "entered a sensory-deprivation tank and emerged with three additional senses, all useless",
      "accepted twenty dollars to let the Bureau alphabetize your organs",
    ],
    escalations: [
      "The control group has since formed a support group about you.",
      "Researchers stopped taking notes and began drafting apologies.",
      "The placebo developed better combat statistics.",
      "Your upgraded organ was repossessed before the trial concluded.",
      "The project was cancelled after success became less ethical than failure.",
    ],
  },
  {
    id: "future",
    incidents: [
      "arrived from 2049 to prevent a disaster and immediately caused the cheaper version",
      "attended your own retirement party seventeen years after your funeral",
      "received a warning from your future clone and blocked it as spam",
      "stole a sports almanac containing only minor-league bowling results",
      "witnessed Earth conquered by a customer-service chatbot with good posture",
      "returned from tomorrow carrying a receipt for today's autopsy",
      "attempted to kill your grandfather but got distracted by brunch",
    ],
    escalations: [
      "The future has since installed caller ID specifically for you.",
      "Your older self described the mission as not worth the parking.",
      "History survived but filed an incident report.",
      "The timeline now flinches whenever you open a calendar.",
      "A paradox was born and currently lists you as dependent.",
    ],
  },
  {
    id: "funeral",
    incidents: [
      "attended a funeral where the deceased kept correcting the eulogy",
      "were hired as a pallbearer despite being the person in the casket",
      "brought an alien resurrection device to the wrong memorial service",
      "mistook embalming fluid for the complimentary punch",
      "sold premium afterlife upgrades from behind the crematorium",
      "lost a corpse during a three-legged race at the wake",
      "delivered a eulogy so poor the body returned to object",
    ],
    escalations: [
      "The family accepted your apology but the deceased did not.",
      "A second coffin was opened solely to create distance.",
      "The crematorium now requires two forms of species identification.",
      "Your name remains on a restraining order from the afterlife.",
      "The corpse later gave you a one-star performance review.",
    ],
  },
  {
    id: "cult",
    incidents: [
      "joined a cosmic fertility cult after misreading the words free buffet",
      "were crowned prophet because the real candidate passed a background check",
      "performed a sacred mating dance that activated a military satellite",
      "drank ceremonial fluid later identified as radiator coolant",
      "founded a doomsday sect whose apocalypse was postponed for weather",
      "sacrificed a fax machine that turned out to be an undercover agent",
      "translated alien scripture into an aggressive multilevel-marketing pitch",
    ],
    escalations: [
      "The followers left after learning heaven had a two-drink minimum.",
      "Your ceremonial robe remains evidence in three unrelated divorces.",
      "The deity answered once, heard your plan, and disconnected.",
      "The compound was raided by the Bureau and one furious health inspector.",
      "Your prophecy came true but only for a nearby Arby's.",
    ],
  },
  {
    id: "classified-employment",
    incidents: [
      "worked night security at a black site despite failing the mammal portion of screening",
      "served as personal assistant to an alien ambassador with six divorces",
      "managed inventory for the Bureau's confiscated buttocks division",
      "operated a neuralyzer kiosk inside an airport Cinnabon",
      "handled corpse returns without the required food-safety certification",
      "trained Reptilian interns using motivational threats and expired yogurt",
      "filed UFO damage claims under the alias Kevin Weather",
    ],
    escalations: [
      "Your exit interview lasted four hours and removed eleven years.",
      "Payroll still classifies you as office furniture.",
      "The ambassador listed your species as a workplace accommodation.",
      "Your pension consists of one haunted pager and store credit.",
      "Human Resources denies you were ever technically alive on company time.",
    ],
  },
];

export const MEMORY_FAMILIES = Object.freeze(
  MEMORY_FAMILY_DATA.map((family) =>
    Object.freeze({
      id: family.id,
      incidents: entries(
        `memory-${family.id}-incident`,
        [
          ...family.incidents,
          ...(MEMORY_FAMILY_EXPANSIONS[family.id]?.incidents ?? []),
        ],
        { tone: "dark", tags: ["medical"] },
      ),
      escalations: entries(
        `memory-${family.id}-escalation`,
        [
          ...family.escalations,
          ...(MEMORY_FAMILY_EXPANSIONS[family.id]?.escalations ?? []),
        ],
        { tone: "spicy" },
      ),
    }),
  ),
);

function tierEntries(prefix, groups) {
  const expansionKey = {
    "threat-class": "classification",
    "threat-capability": "capability",
    "threat-attack": "attack",
    "threat-defense": "defense",
    "threat-weakness": "weakness",
    "threat-casualty": "casualty",
    "threat-containment": "containment",
  }[prefix];
  const expansionGroups = THREAT_TIER_EXPANSIONS[expansionKey] ?? [];
  return Object.freeze(
    groups.flatMap((texts, tier) =>
      [...texts, ...(expansionGroups[tier] ?? [])].map((text, index) =>
        Object.freeze({
          id: `${prefix}-t${tier}-${String(index + 1).padStart(2, "0")}`,
          text,
          weight: 1,
          tone: tier >= 4 ? "dark" : "standard",
          tags: [],
          families: [],
          tiers: [tier],
        }),
      ),
    ),
  );
}

export const THREAT_CLASSIFICATIONS = tierEntries("threat-class", [
  [
    "Mostly Harmless Office Plant",
    "Noncombatant With Opinions",
    "Decorative Mammal",
    "Low-Voltage Nuisance",
    "Probationary Organism",
  ],
  [
    "Weaponized Incompetence",
    "Minor Social Biohazard",
    "Unlicensed Kitchen Combatant",
    "Localized Vibe Disruption",
    "Low-Orbit Embarrassment",
  ],
  [
    "Interstate Menace",
    "Tactical Bathroom Hazard",
    "Class-2 Chaos Merchant",
    "Aggressively Mobile Liability",
    "Containment-Adjacent Dumbass",
  ],
  [
    "Regional Reality Offender",
    "Federal Upholstery Threat",
    "Class-3 Biological Misprint",
    "Armed Administrative Failure",
    "Hostile Witness to Common Sense",
  ],
  [
    "Planetary Liability",
    "Mass-Casualty Group Chat Event",
    "Omega-Level Bad Decision",
    "Weaponized Meat Emergency",
    "Civil Defense Regret",
  ],
  [
    "Civilization-Ending Dumbass",
    "Extinction-Class HR Complaint",
    "Cosmic Final Notice",
    "Reality Foreclosure Event",
    "Do Not Approach in This Timeline",
  ],
]);

export const COMBAT_CAPABILITIES = tierEntries("threat-capability", [
  [
    "Can lose a fistfight to a fitted sheet.",
    "Maximum lift capacity: one emotionally supportive grocery bag.",
    "Combat stance resembles waiting for a public restroom.",
    "Has never defeated stairs without witnesses.",
    "Reaction time measured using a sundial.",
    "Primary muscle group remains theoretical.",
    "Qualified only for turn-based conflict.",
  ],
  [
    "Can weaponize a folding chair if instructions are pictorial.",
    "Possesses the confidence of three larger men.",
    "Throws punches with excellent forwarding addresses.",
    "Capable of minor property damage and major explanations.",
    "Can sprint briefly when a check arrives.",
    "Has one combat-certified elbow and no warranty.",
    "Danger increases near unattended power tools.",
  ],
  [
    "Can convert embarrassment into short-range kinetic force.",
    "Demonstrates advanced pocket-sand doctrine.",
    "Body contains several load-bearing grudges.",
    "Can survive two consecutive consequences.",
    "Operates improvised weapons with retail-level competence.",
    "Has bitten through one legally distinct restraint.",
    "Can summon backup by lying about free food.",
  ],
  [
    "Able to rupture drywall using only unresolved childhood energy.",
    "Combat organs appear to rotate shifts.",
    "Can weaponize nearby furniture without union approval.",
    "Possesses a black belt from an online university.",
    "Produces concussive disappointment at conversational range.",
    "Can tank one Noisy Cricket blast if sufficiently confused.",
    "Has defeated a police horse in an argument.",
  ],
  [
    "Generates blast pressure whenever accountability approaches.",
    "Can disable regional Wi-Fi through pelvic rotation.",
    "Carries enough unstable confidence to breach concrete.",
    "Has three confirmed kills, all against workplace morale.",
    "Can turn a parking dispute into federal mobilization.",
    "Anatomy supports limited anti-vehicle operations.",
    "Capable of weaponizing the nearest emergency contact.",
  ],
  [
    "Can suplex local gravity for approximately nine seconds.",
    "Emits extinction-grade force when left on read.",
    "Capable of defeating an armored division through bad logistics.",
    "Can convert one energy drink into orbital bombardment.",
    "Contains a self-guided apocalypse behind the sternum.",
    "Has beaten causality in two out of three bar fights.",
    "Combat output requires a separate disaster declaration.",
  ],
]);

export const PRIMARY_ATTACKS = tierEntries("threat-attack", [
  [
    "an unsolicited voice message exceeding four minutes",
    "a limp handshake with no exit strategy",
    "weaponized oversharing",
    "a strongly worded typo",
    "the same joke repeated at closer range",
    "passive-aggressive breathing",
  ],
  [
    "a gas-station energy drink sprayed from the nostrils",
    "tactical pocket lint",
    "a folding chair used below manufacturer speed",
    "a Bluetooth speaker playing one damaged file",
    "a confusing but committed headbutt",
    "short-range emotional debris",
  ],
  [
    "a Noisy Cricket held sideways for credibility",
    "compressed body odor projected in a cone",
    "an ankle-mounted tractor beam",
    "a throwable jar of residual personality",
    "illegal elbow firmware",
    "a clone deployed without quality assurance",
  ],
  [
    "a pelvic EMP capable of disabling pacemakers and podcasts",
    "an autopsy laser concealed inside a vape",
    "a swarm of debt-collecting Worm Guys",
    "reanimated furniture moving at highway speed",
    "a federal-grade shame cannon",
    "a saucer strike ordered through a food-delivery app",
  ],
  [
    "a regional neuralyzer burst without informed consent",
    "weaponized organ rejection",
    "an antimatter tantrum",
    "a tactical corpse with unresolved loyalty",
    "a tractor beam loaded with municipal waste",
    "a black-site payroll system released into civilian networks",
  ],
  [
    "a reality-ending group notification",
    "the forced merger of two incompatible timelines",
    "orbital bombardment powered by sexual frustration",
    "an extinction pulse emitted from the lower intestine",
    "a self-replicating customer complaint",
    "the Moon used as an improvised blunt instrument",
  ],
]);

export const DEFENSIVE_RESPONSES = tierEntries("threat-defense", [
  [
    "Plays dead, but without improving the room.",
    "Hides behind the nearest employed adult.",
    "Attempts to disconnect from the encounter.",
    "Forms a defensive fetal spreadsheet.",
    "Claims the attack violates store policy.",
    "Deploys one coupon as legal shield.",
  ],
  [
    "Releases a cloud of vape smoke and disputed facts.",
    "Uses a folding chair as emotional armor.",
    "Blames swamp gas until the attacker loses interest.",
    "Deploys a decoy search history.",
    "Calls their mother on speakerphone.",
    "Retreats through a door clearly marked pull.",
  ],
  [
    "Sheds one disposable personality.",
    "Hides inside a recently deceased clone.",
    "Redirects damage to an unpaid intern.",
    "Deploys a counterfeit diplomatic passport.",
    "Creates a low-budget hologram with better posture.",
    "Uses secondhand embarrassment as ablative armor.",
  ],
  [
    "Activates a Bureau-rejected forcefield.",
    "Temporarily relocates organs to Delaware.",
    "Summons three raccoons with qualified immunity.",
    "Converts incoming fire into medical debt.",
    "Encases the body in weaponized funeral upholstery.",
    "Neuralyzes the concept of having been hit.",
  ],
  [
    "Folds local space into a nonrefundable warranty.",
    "Deploys a tactical duplicate legally considered furniture.",
    "Redirects missiles into a neighboring timeline.",
    "Uses a corpse wall with active union representation.",
    "Triggers emergency planetary caller ID.",
    "Turns nearby atmosphere into hostile paperwork.",
  ],
  [
    "Places the entire battle under federal seal.",
    "Deletes the attacker's childhood from continuity.",
    "Hides behind a backup universe.",
    "Converts death into a recurring subscription.",
    "Deploys causality as a human shield.",
    "Files for diplomatic immunity from physics.",
  ],
]);

export const THREAT_WEAKNESSES = tierEntries("threat-weakness", [
  SCAN_WEAKNESSES.slice(0, 7).map((entry) => entry.text),
  SCAN_WEAKNESSES.slice(7, 14).map((entry) => entry.text),
  SCAN_WEAKNESSES.slice(14, 21).map((entry) => entry.text),
  SCAN_WEAKNESSES.slice(21, 28).map((entry) => entry.text),
  SCAN_WEAKNESSES.slice(28, 35).map((entry) => entry.text),
  SCAN_WEAKNESSES.slice(35, 42).map((entry) => entry.text),
]);

export const LIKELY_CASUALTIES = tierEntries("threat-casualty", [
  [
    "one beverage and the subject's remaining credibility",
    "a folding chair with pre-existing damage",
    "the nearest quiet conversation",
    "one unpaid intern's lunch break",
    "a small amount of government patience",
  ],
  [
    "three houseplants and a Bluetooth speaker",
    "one regional brunch service",
    "a Roomba responding to the scene",
    "the drywall nearest an emotional outburst",
    "two friendships already on probation",
  ],
  [
    "an entire bowling league and one innocent urinal",
    "six parked cars with no narrative relevance",
    "the county's supply of clean towels",
    "a moderately successful wedding reception",
    "every sober adult within shouting distance",
  ],
  [
    "a suburban zip code and its least popular dentist",
    "three livestock herds and one skeptical coroner",
    "the Bureau's western upholstery reserve",
    "a freeway interchange with children",
    "the concept of a normal Thursday",
  ],
  [
    "two states, one moon, and a heavily insured Applebee's",
    "regional civilization plus the good Costco",
    "every clone produced this fiscal quarter",
    "the Atlantic seaboard's remaining dignity",
    "an election cycle and several innocent dimensions",
  ],
  [
    "Earth, its backup, and whoever approved the budget",
    "all mammalian life except one extremely lucky raccoon",
    "causality across six inhabited timelines",
    "the solar system's security deposit",
    "the universe, followed by a nonrefundable processing fee",
  ],
]);

export const CONTAINMENT_PROTOCOLS = tierEntries("threat-containment", [
  [
    "Offer snacks and disconnect the controller.",
    "Place behind a baby gate rated for emotional loads.",
    "Distract with a menu containing photographs.",
    "Ask one follow-up question and wait.",
    "Turn off the lights and pretend the building closed.",
  ],
  [
    "Deploy a sober adult carrying a fitted sheet.",
    "Confine inside a karaoke booth with no power.",
    "Use two interns and a restaurant pager.",
    "Remove Wi-Fi and observe from behind glass.",
    "Issue a firm no and reinforce the drywall.",
  ],
  [
    "Deploy one neuralyzer and a veterinarian with tenure.",
    "Seal the room with gas-station caution tape.",
    "Bait containment using loaded fries.",
    "Assign three Worm Guys and a folding chair.",
    "Suspend the subject's operating license from humanity.",
  ],
  [
    "Evacuate the county and activate the shame cannon.",
    "Use a Class-3 forcefield and sacrificial Roomba.",
    "Freeze all visible organs before transport.",
    "Confine inside a decommissioned Bass Pro Shops pyramid.",
    "Deploy Agent J with the good sunglasses.",
  ],
  [
    "Relocate the target to a timeline with stronger building codes.",
    "Deploy orbital duct tape and deny media access.",
    "Surround with six neuralyzers pointed inward.",
    "Transfer to the Moon under false pretenses.",
    "Seal inside the federal evidence freezer indefinitely.",
  ],
  [
    "Abandon this timeline and remove it from navigation.",
    "Use the Moon as a lid and pray quietly.",
    "Initiate universal factory reset.",
    "Offer the subject management and wait for collapse.",
    "There is no protocol; Agent J recommends running stylishly.",
  ],
]);

export const SENSOR_CONFIDENCE = expandedEntries("sensor-confidence", [
  "99% — both sensors and one terrified priest agree",
  "95% — confirmed by orbital dental records",
  "90% — independent corpse verification obtained",
  "84% — readings stable despite the smell",
  "78% — one instrument has requested hazard pay",
  "71% — enough certainty to leave town",
  "64% — scanner survived with minor emotional damage",
  "57% — coin flip enhanced by federal funding",
  "50% — perfectly balanced and equally irresponsible",
  "43% — target may be standing near the actual threat",
  "35% — atmospheric ranch dressing detected",
  "26% — device calibrated by a Worm Guy",
  "18% — measurements violate two mammal standards",
  "9% — sensor keeps returning the word moist",
  "2% — still more confidence than Agent J has in the subject",
]);
